# We will use docker to set up out environment, so don't use any particular
# language in Travis itself
language: generic

# Enable docker
sudo: required
services:
    - docker

# Disable automatic submodule fetching (it's done recursively)
git:
    submodules: false

# Do a shallow submodule fetch
before_install: git submodule update --init

env:
    global:
        # Make sure beaver is in the PATH
        - PATH="$(git config -f .gitmodules submodule.beaver.path)/bin:$PATH"
        - DIST=bionic
        - COV=0

# Basic config is inherited from the global scope
jobs:
    templates:
        - &test-matrix
          stage: Test
          after_success: beaver dlang codecov
          install: beaver dlang install
          script: beaver dlang make

    include:
        # Test matrix
        - <<: *test-matrix
          env: DMD=2.092.* F=production
        - <<: *test-matrix
          env: DMD=2.092.* F=devel
        - <<: *test-matrix
          env: DMD=2.093.* F=production COV=1
        - <<: *test-matrix
          env: DMD=2.093.* F=devel COV=1

        # Additional stages

        - stage: Closure allocation check
          env: DMD=2.093.* F=devel
          install: beaver dlang install
          script: ci/closures.sh
